services:
  - type: web
    name: paxton-md
    runtime: node
    repo: https://github.com/jarvismd98-afk/Paxton-Md
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PREFIX
        value: "."
      - key: OWNER_NUMBER
        value: "166602502836424"
